In [19]:
import numpy as np

In [20]:
def get_mnist(flag):
    with np.load(f"./data/mnist.npz") as f:
        images, labels = f[f"x_{flag}"], f[f"y_{flag}"]
    images = images.astype("float32") / 255
    images = np.reshape(images, (images.shape[0], images.shape[1] * images.shape[2]))
    labels = np.eye(10)[labels]
    return images, labels

In [21]:
X_train, y_train = get_mnist(flag="train")
X_test, y_test = get_mnist(flag="test")
X_val, y_val = X_train[50000:60000,:], y_train[50000:60000] # tập validation
X_train, y_train = X_train[:50000,:], y_train[:50000]

In [22]:
# support function

def softmax(z):
    exp_z = np.exp(z - np.max(z, axis=1, keepdims=True))
    return exp_z / np.sum(exp_z, axis=1, keepdims=True)
def gradient_descent(X, y, theta, alpha, num_iterations):
    m = len(y)
    num_classes = len(np.unique(y))
    for _ in range(num_iterations):
        h = softmax(np.dot(X, theta))
        gradient = np.dot(X.T, (h - (np.arange(num_classes) == y[:, None]).astype(float))) / m
        theta -= alpha * gradient
    return theta


In [23]:
# Set hyperparameters
alpha = 0.01
num_iterations = 1000

In [24]:
theta = np.zeros((X_train.shape[1], y_train.shape[1]))

In [25]:
theta = gradient_descent(X_train, np.argmax(y_train, axis=1), theta, alpha, num_iterations)

In [26]:
# Predictions on the test set
test_probabilities = softmax(np.dot(X_test, theta))
predictions = np.argmax(test_probabilities, axis=1)

# Calculate accuracy
accuracy = np.mean(predictions == np.argmax(y_test, axis=1))
print("Accuracy:", accuracy)

Learned parameters:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Accuracy: 0.872
